## flair_test_suite.toml
```toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flair-automate"
version = "0.1.0"
authors = [{name = "Your Name", email = "you@example.com"}]
description = "Per-region FLAIR automation CLI"
readme = "README.md"
requires-python = ">=3.11"

[project.urls]
"Homepage" = "https://github.com/yourrepo/flair-test-suite"

[project.dependencies]
# list runtime dependencies here

t[project.scripts]
flair-test-suite = "flair_automate.cli:main"
```