# ------------------------------------------------------------------------------------------------------------
# Align -> Transcriptome Configuration
# ------------------------------------------------------------------------------------------------------------
# -------------------------------------------- Test Case Description -----------------------------------------
#
# - Organism:
# - Sample(s):
# - Assembly:
# - Platform:
#
# -------------------------------------------- Summary
#
# ------------------------------------------------------------------------------------------------------------

run_id  = ""       # base-name to save under (eg. "WTC11")

[run]
version    = ""    # version of FLAIR (eg. "2.0.0")
conda_env  = ""    # name of user installed conda FLAIR env (eg. "flair2")
work_dir   = ""    # where output will be saved - relative to test suite (eg. "./outputs")

# shared inputs
data_dir   = ""         # where data lives for run
reads_file = ""         # reads fasta
genome_fa  = ""     # reference genome fasta
gtf = ""             # annotation GTF
regions_tsv = ""    # (eg regions_of_interest.tsv)
junctions = ""                                        # optional
experiment_5_prime_regions_bed_file = ""  # optional
experiment_3_prime_regions_bed_file = ""  # optional
reference_5_prime_regions_bed_file =  ""  # optional
reference_3_prime_regions_bed_file =  ""  # optional

# ------------------------------------------------------------------------------------------------------------
# -------- ALIGN ------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------

[[run.stages]]
name = "align"

[run.stages.flags]

# ------------------------------------------------------------------------------------------------------------
# -------- TRANSCRIPTOME ----------------------------------------------------
# ------------------------------------------------------------------------------------------------------------

[[run.stages]]
name = "transcriptome"
requires = ["align"]

[run.stages.flags]

# ------------------------------------------------------------------------------------------------------------
# -------- QUANTIFY ----------------------------------------------------
# ------------------------------------------------------------------------------------------------------------

[[run.stages]]
name = "quantify"
requires = ["transcriptome"]

[run.stages.flags]
manifest = ""  # optional

