# ------------------------------------------------------
# config_template.toml
# ------------------------------------------------------

# ------------------------------------------------------
# Sample Identifier
# ------------------------------------------------------
sample_name = "WTC_11_PacBio"

# ------------------------------------------------------
# Summary of Run
# ------------------------------------------------------
summary = """
This TOML configuration file defines a real-dataset FLAIR test-suite run.
It captures:
  • Dataset metadata (organism, origin, library prep, etc.)
  • Region selection (chromosome ranges to process)
  • Stage-specific flag options (align, correct, collapse, quantify)
  • Passing metrics thresholds for each stage
  • Embedded documentation on how to configure regions and flags
"""

# ------------------------------------------------------
# Base directory for all input files
# ------------------------------------------------------
input_root    = "tests/data"

# ------------------------------------------------------
# Whole Sample Mode (*Set false if running by region)
# ------------------------------------------------------
whole_sample  = false

# ------------------------------------------------------
# Run ID
# ------------------------------------------------------
run_id        = 1

# ------------------------------------------------------
# Version configuration
# ------------------------------------------------------
[run]
version       = "2.0.0"
conda_env     = "flair2"

# ------------------------------------------------------
# Region Selection Summary
# ------------------------------------------------------
[documentation.region_selection]
description = """
• Specify one or more chromosomal regions under [[run.regions]].
• Each entry has:
    chr    = chromosome name (e.g. "chr1")
    ranges = array of "start:end" strings.
• Multiple blocks allow multi‑region runs.
"""

# ------------------------------------------------------
# Region configuration (*empty if running whole sample)
# ------------------------------------------------------
[[run.regions]]
chr    = "chr20"
ranges = ["3218000:3250000"]

# ------------------------------------------------------
# Stage Summaries
# ------------------------------------------------------
[documentation.steps.align]
description = """
• The ‘align’ stage maps reads to the reference genome.
• Common flags:
    threads   = number of CPU threads
    aligner   = choice of aligner (e.g., "flair align", "minimap2")
"""

[documentation.steps.correct]
description = """
• The ‘correct’ stage refines splice junctions.
• Common flags:
    threads     = CPU threads
    junc        = path to junctions file
    ss_window   = splice‑site window size (optional)
"""

[documentation.steps.collapse]
description = """
• The ‘collapse’ stage merges reads into representative isoforms.
• Common flags:
    support       = minimum read support
    check_splice  = boolean to enforce splice validation
    filter        = filtering stringency ("stringent", "best-only", etc.)
    threads       = CPU threads
"""

[documentation.steps.quantify]
description = """
• The ‘quantify’ stage counts reads per isoform.
• Common flags mirror collapse (support, check_splice, filter, threads).
"""

# ------------------------------------------------------
# Single dataset definition + metadata
# ------------------------------------------------------
[data_dir]
name                 = "human_GENCODEv48_WTC11_PacBio_CAGE_QuantSeq"
reads_fasta          = "WTC11.100reads.fasta"
genome_fasta         = "GRCh38.primary_assembly.genome.fa"
annotation_gtf       = "gencode.v48.annotation.gtf"
junctions            = "WTC11_all.SJ.out.tab"
ref_tss_bed          = "human_ref_TSS.bed"
ref_tts_bed          = "human_ref_TTS.bed"
experimental_tss_bed = "CAGE_TSS_human.bed"
experimental_tts_bed = "WTC11_all_polyApeaks_fixed.bed"

  [data_dir.metadata]
  sample                                 = "WTC11"
  organism                               = "Human"
  platform                               = "PacBio"
  replicates                             = 3
  dataset_origin                         = "real"            # "real" vs. "simulated"
  experimental__5_prime_end_library_prep = "CAGE"
  experimental__3_prime_end_library_prep = "QuantSeq"

# ------------------------------------------------------
# Flags for each stage (one option per stage)
# ------------------------------------------------------
[run.steps.align.flags]
threads = 4

[run.steps.correct.flags]
threads = 12
junc    = "${input_root}/${run.data_dir}/WTC11_all.SJ.out.tab"

[run.steps.collapse.flags]
support      = 1
check_splice = true
filter       = "stringent"
threads      = 8

[run.steps.quantify.flags]
support      = 1
check_splice = true
filter       = "stringent"
threads      = 8

# ------------------------------------------------------
# Passing metrics thresholds for QC per stage
# ------------------------------------------------------
[run.metrics.align]
exists     = true
rate_range = "0.85-0.95"

[run.metrics.correct]
exists          = true
accuracy_range  = "0.90-1.00"

[run.metrics.collapse]
exists               = true
isoform_count_range  = "50-150"

[run.metrics.quantify]
exists          = true
precision_range = "0.80-0.90"
