# combine: Merge isoform sets from upstream collapse/transcriptome
# Behavior: auto-discovers upstream isoform BED/FA/map and appends to manifest
# Outputs: <id>.{bed,fa,counts.tsv,isoform.map.txt}
[[run.stages]]
name = "combine"

[run.stages.flags]
# Provide an existing manifest to append to (optional).
# You can copy and edit: config/templates/combine_manifest_template.tsv
# manifest = "combine_manifest.tsv"
# Ordering: after collapse/transcriptome
