# correct: Correct splice junctions from upstream alignment (per-region when regionalized)
# Consumes: align/regionalize BED
# Outputs: <id>_all_corrected.bed or {tag}_all_corrected.bed; per-region QC under qc/<tag>/
[[run.stages]]
name = "correct"

[run.stages.flags]
# Put any correct flags here. For FLAIR >= 3, genome is not required.

# Ordering: place after align (or after regionalize for targeted runs)
