# ------------------------------------------------------------------------------------------------------------
# Inputs (shared, no stages)
# ------------------------------------------------------------------------------------------------------------
# Provide test_set_id here for identifying the test case.
test_set_id = ""   # e.g., "WTC11" (required)

# Outputs are always written under ./outputs/<test_set_id>/ with a run_summary.log in the same folder.

[run]
version    = ""        # flair version, e.g. "3.0.0"
conda_env  = ""        # conda env with FLAIR, e.g. "flair"

# Shared inputs (resolved relative to data_dir unless absolute)
data_dir   = ""        # directory containing all input data
reads_file = ""        # FASTA/Q or comma/list of files; gz ok
genome_fa  = ""        # reference genome FASTA
gtf        = ""        # annotation GTF (required for regionalize)
regions_tsv = ""       # 3-column TSV (chr start end) for regionalize

# If provided, SQANTI QC will run automatically using this environment.
sqanti_env  = ""       # e.g., "sqanti" (preferred conda env name for SQANTI)

# Optional shared inputs
junctions = ""                                        # STAR SJ.out.tab (optional)
experiment_5_prime_regions_bed_file = ""              # optional for TED QC (enables precision/recall if provided)
experiment_3_prime_regions_bed_file = ""              # optional for TED QC (enables precision/recall if provided)
reference_5_prime_regions_bed_file  = ""              # optional for TED QC (enables precision/recall if provided)
reference_3_prime_regions_bed_file  = ""              # optional for TED QC (enables precision/recall if provided)

# Note: TED QC runs automatically for collapse/transcriptome stages. Peak BEDs above are optional; without them, precision/recall are None.
