[[run.stages]]
name = "quantify"

[run.stages.flags]
# quantify: Compute expression from upstream isoform FASTA
# Needs: reads manifest (sample\tcondition\tbatch\treads.fq)
# Behavior: auto-selects isoform FASTA from combine/transcriptome/collapse
# Outputs: <id>.counts.tsv (+ tool-native files)
# You can copy and edit: config/templates/quantify_reads_manifest_template.tsv
manifest = "reads_manifest.tsv"

# Ordering: after the stage producing isoform FASTA (combine/transcriptome/collapse)
