[[run.stages]]
name = "transcriptome"

[run.stages.flags]
# Add transcriptome flags here.
# Ordering: place this after 'align' (or after 'regionalize' if using regionalized path).

# Optional QC notes:
# - TED runs automatically with a fixed window of 50 (no block needed). Providing
#   peak BEDs under [run] enables precision/recall; otherwise those metrics are None.
# - SQANTI runs automatically when available (conda env named 'sqanti' or entrypoint
#   on PATH). Use the block below only to override env name or CPUs.

[qc.transcriptome.SQANTI]
# conda_env = "sqanti"   # override env name if not 'sqanti'
# cpus = 8
